export { default as Table } from './Table'
export { default as THead } from './Head'
export { default as Th } from './Th'
export { default as TBody } from './Body'
export { default as Tr } from './Tr'
export { default as Td } from './Td'
